package interpretador;

public enum TipoToken {

    IDENTIFICADOR,
    CONSTANTE_INTEIRA,
    CONSTANTE_FLOAT,
    CONSTANTE_BOOLEANA,
    CONSTANTE_DOUBLE,
    CONSTANTE_CHAR,
    ABRE_PARENTESES,
    FECHA_PARENTESES,
    OPERADOR_ATRIBUICAO,
    OPERADOR_ARITMETICO,
    OPERADOR_RELACIONAL,
    OPERADOR_LOGICO,
    FIM_COMANDO,
    SEPARADOR_ARGUMENTO,
    TIPO_DADO,
    PALAVRA_RESERVADA,
    INICIO_ESCOPO,
    FIM_ESCOPO,
    INCREMENTO,
    DECREMENTO,
    INCREMENTO_IGUAL,
    DECREMENTO_IGUAL,
}

